apiVersion: apps/v1
kind: Deployment
metadata:
  name: gemma-clientapp-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gemma-clientapp-2
  template:
    metadata:
      labels:
        app: gemma-clientapp-2
    spec:
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-tesla-a100
      tolerations:
      - key: "nvidia.com/gpu"
        operator: "Exists"
        effect: "NoSchedule"
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - gemma-serverapp
                - gemma-clientapp-1
                - gemma-clientapp-2
            topologyKey: "kubernetes.io/hostname"
      containers:
      - name: clientapp
        image: us-central1-docker.pkg.dev/privacy-ml-lab2/flower/flwr/gemma_clientapp:1.3
        args: 
          - "--insecure"
          - "--clientappio-api-address"
          - "supernode-2-service:9094"
        resources:
          limits:
            nvidia.com/gpu: 1
