apiVersion: apps/v1
kind: Deployment
metadata:
  name: superlink
spec:
  replicas: 1
  selector:
    matchLabels:
      app: superlink
  template:
    metadata:
      labels:
        app: superlink
    spec:
      containers:
      - name: superlink
        image: us-central1-docker.pkg.dev/privacy-ml-lab2/flower/flwr/superlink:1.16.0
        args: 
          - "--insecure"
          - "--isolation"
          - "process"
        ports:  # which ports to expose/available
        - containerPort: 9091
        - containerPort: 9092
        - containerPort: 9093
---
apiVersion: v1
kind: Service
metadata:
  name: superlink-service
spec:
  selector:
    app: superlink
  ports:  # like a dynamic IP routing table/mapping that routes traffic to the designated ports
  - protocol: TCP
    port: 9091   # Port for ServerApp connection
    targetPort: 9091  # the SuperLink container port
    name: superlink-serverappioapi
  - protocol: TCP
    port: 9092   # Port for SuperNode connection
    targetPort: 9092  # the SuperLink container port
    name: superlink-fleetapi
  - protocol: TCP
    port: 9093   # Port for Flower applications
    targetPort: 9093  # the SuperLink container port
    name: superlink-execapi
  type: LoadBalancer  # balances workload, makes the service publicly available