apiVersion: apps/v1
kind: Deployment
metadata:
  name: supernode-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supernode-2
  template:
    metadata:
      labels:
        app: supernode-2
    spec:
      containers:
      - name: supernode
        image: us-central1-docker.pkg.dev/privacy-ml-lab2/flower/flwr/supernode:1.16.0
        args:
          - "--insecure"
          - "--superlink"
          - "superlink-service:9092"
          - "--clientappio-api-address"
          - "0.0.0.0:9094"
          - "--isolation"
          - "process"
          - "--node-config"
          - "partition-id=1 num-partitions=2"
        ports:
        - containerPort: 9094
---
apiVersion: v1
kind: Service
metadata:
  name: supernode-2-service
spec:
  selector:
    app: supernode-2
  ports:
  - protocol: TCP
    port: 9094
    targetPort: 9094
